### ISSUE TITLE
Got an error using the webapp to connect the card.

### ISSUE THREAD

**Issue by dannyyaou** [CoolBitX-Technology/coolwallet-signing-tools#24]
Got an error using the webapp to connect the card.

Please find error below:

Unhandled Rejection (Error): error function: executeAPDU, message: executeAPDU error: NotSupportedError: GATT operation failed for unknown reason.

<img width="1063" alt="Screenshot 2022-01-05 at 10 16 34 AM" src="https://user-images.githubusercontent.com/8759099/148150061-d320efe9-994b-4f5f-a8ad-00ea5897cc94.png">

**Comment by skchang0710** [comment]
It was due to MacOS issues and has been fixed since MacOS 12.3.0
